language: node_js
node_js:
  - "9"
stages:
  - precache
  - lint
  - test
  - release
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
# this avoids compilation in most cases (where we don't need it)
install: npm ci --ignore-scripts
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

jobs:
  include:
    - stage: precache
      script: true
    - stage: lint
        script:
          - npm run lint-ci
    - stage: test
      script:
        - npm run test
    - stage: release
      if: tag IS present AND branch = master
      node_js: "8"
      script: npm build-prod
      deploy:
        provider: npm
        email: "$NPM_EMAIL$"
        api_key: "$NPM_TOKEN$"
        skip_cleanup: true
        on:
          tags: true

notifications:
  webhooks:
    urls:
      - "$GITTER_WEBHOOK"
    on_success: change
    on_failure: always
    on_start: never
