language: node_js
node_js:
  - "8"
  - "9"
stages:
  - test
  - npm release
jobs:
  include:
    - stage: test
      script:
        - npm run lint-ci
        - npm run test
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: npm build-prod
      deploy:
        provider: npm
        email: "$NPM_EMAIL$"
        api_key: "$NPM_TOKEN$"
        skip_cleanup: true
        on:
          tags: true
