###
### .travis.yml
###

# these are executed in order.  each must pass for the next to be run
stages:
  - precache
  - lint
  - test
  - coverage
  - release

# defaults
language: node_js
node_js: '8'
addons:
  apt:
    packages:
      - libnotify-bin
# `nvm install` happens before the cache is restored, which means
# we must install our own npm elsewhere (`~/npm`)
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
# this avoids compilation in most cases (where we don't need it)
install: npm ci --ignore-scripts
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

jobs:
  include:
    - stage: precache
      script: true
    - stage: lint
      script:
        - npm run lint-ci
    - stage: test
      node_js:
        - "8"
        - "9"
        - "11"
      script:
        - npm run test && ls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: release
      if: tag IS present
      script: npm run build-prod
      deploy:
        provider: npm
        email: "$NPM_EMAIL$"
        api_key: "$NPM_TOKEN$"
        skip_cleanup: true
        on:
          tags: true

notifications:
  email: false
  webhooks:
    urls:
      - "$GITTER_WEBHOOK$"
    on_success: change
    on_failure: always
    on_start: never
